name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          components: clippy, rustfmt

      - name: Format
        run: cargo fmt --all -- --check

      - name: Install LLVM
        run: sudo apt-get install -y llvm

      - name: Install cargo-xwin
        run: cargo install cargo-xwin

      - name: Clippy
        run: cargo xwin clippy --release --target x86_64-pc-windows-msvc -- -D warnings

      - name: Build
        run: cargo xwin build --release --target x86_64-pc-windows-msvc

      - name: Compress
        if: github.event_name == 'workflow_dispatch'
        working-directory: target/x86_64-pc-windows-msvc/release
        run: 7z a -mx=9 ${{ github.workspace }}/umpv-rust.7z umpv.exe

      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7
        with:
          name: umpv
          path: umpv-rust.7z
          retention-days: 7
